export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const SELECT_FILEPATH = 'SELECT_FILEPATH';
export const CLEAR_FILEPATH = 'CLEAR_FILEPATH';

export const SYNC_DEBOUNCE_START = 'SYNC_DEBOUNCE_START';
export const SYNC_START = 'SYNC_START';
export const SYNC_SUCCESS = 'SYNC_SUCCESS';
export const SYNC_FAILURE = 'SYNC_FAILURE';